Presentation/ExpertSender.WebApp/Models/ErrorViewModel.cs
using System;

namespace ExpertSender.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Presentation/ExpertSender.WebApp/Controllers/EmailController.cs
using ExpertSender.DTOs;
using ExpertSender.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Serilog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpertSender.WebApp.Controllers
{
    public class EmailController : Controller
    {
        private ILogger _log => Log.ForContext<EmailController>();

        public async Task<IActionResult> Index()
        {
            IEnumerable<EmailDTO> emails = Enumerable.Empty<EmailDTO>();

            try
            {
                if (TempData["error"] != null)
                    ModelState.AddModelError(string.Empty, TempData["error"].ToString());

                string result = await HttpClientExtension.HttpGet("email");
                emails = JsonConvert.DeserializeObject<IEnumerable<EmailDTO>>(result);

                string resultPersons = await HttpClientExtension.HttpGet("person");
                IEnumerable<PersonDTO> persons = JsonConvert.DeserializeObject<IEnumerable<PersonDTO>>(resultPersons);

                if (!persons.Any())
                {
                    _log.Here().Information("Person list is empty");
                    throw new Exception("Person list is empty");
                }

                ViewBag.Person = persons.LastOrDefault();
            }
            catch (Exception ex)
            {
                _log.Here().Error(ex.GetBaseException().Message);
                ModelState.AddModelError(string.Empty, ex.GetBaseException().Message);
            }

            return View(emails);
        }

        public async Task<IActionResult> BasicForm(int? emailId)
        {
            EmailDTO email = null;
            IEnumerable<PersonDTO> persons = Enumerable.Empty<PersonDTO>();

            try
            {
                if (emailId != null)
                {
                    string resultEmail = await HttpClientExtension.HttpGet("email", emailId);
                    email = JsonConvert.DeserializeObject<EmailDTO>(resultEmail);
                }

                string resultPersons = await HttpClientExtension.HttpGet("person");
                persons = JsonConvert.DeserializeObject<IEnumerable<PersonDTO>>(resultPersons);

                if (!persons.Any())
                {
                    _log.Here().Information("Person list is empty");
                    throw new Exception("Person list is empty");
                }

                ViewBag.Persons = new SelectList(persons, "Id", "FullName");
            }
            catch (Exception ex)
            {
                _log.Here().Error(ex.GetBaseException().Message);
                ModelState.AddModelError(string.Empty, ex.GetBaseException().Message);
            }

            return View(email);
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmailDTO email)
        {
            try
            {
                await HttpClientExtension.HttpCreate(email);
            }
            catch (Exception ex)
            {
                _log.Here().Error(ex.GetBaseException().Message);
                TempData["error"] = ex.GetBaseException().Message;
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Update(EmailDTO email)
        {
            try
            {
                await HttpClientExtension.HttpUpdate(email);
            }
            catch (Exception ex)
            {
                _log.Here().Error(ex.GetBaseException().Message);
                TempData["error"] = ex.GetBaseException().Message;
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int emailId)
        {
            try
            {
                await HttpClientExtension.HttpDelete("email", emailId);
            }
            catch (Exception ex)
            {
                _log.Here().Error(ex.GetBaseException().Message);
                TempData["error"] = ex.GetBaseException().Message;
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Presentation/ExpertSender.WebApp/Controllers/HomeController.cs
using ExpertSender.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace ExpertSender.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Presentation/ExpertSender.WebApp/Controllers/PersonController.cs
using ExpertSender.DTOs;
using ExpertSender.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Serilog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpertSender.WebApp.Controllers
{
    public class PersonController : Controller
    {
        private ILogger _log => Log.ForContext<PersonController>();

        public async Task<IActionResult> Index()
        {
            IEnumerable<PersonDTO> persons = Enumerable.Empty<PersonDTO>();

            try
            {
                if (TempData["error"] != null)
                    ModelState.AddModelError(string.Empty, TempData["error"].ToString());

                string result = await HttpClientExtension.HttpGet("person");
                persons = JsonConvert.DeserializeObject<IEnumerable<PersonDTO>>(result);
            }
            catch (Exception ex)
            {
                _log.Here().Error(ex.GetBaseException().Message);
                ModelState.AddModelError(string.Empty, ex.GetBaseException().Message);
            }

            return View(persons);
        }

        public async Task<IActionResult> BasicForm(int? personId)
        {
            PersonDTO person = null;

            try
            {
                if (personId != null)
                {
                    string personResult = await HttpClientExtension.HttpGet("person", personId);
                    person = JsonConvert.DeserializeObject<PersonDTO>(personResult);
                }
            }
            catch (Exception ex)
            {
                _log.Here().Error(ex.GetBaseException().Message);
                ModelState.AddModelError(string.Empty, ex.GetBaseException().Message);
            }

            return View(person);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PersonDTO person)
        {
            try
            {
                await HttpClientExtension.HttpCreate(person);
            }
            catch (Exception ex)
            {
                _log.Here().Error(ex.GetBaseException().Message);
                TempData["error"] = ex.GetBaseException().Message;
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Update(PersonDTO person)
        {
            try
            {
                await HttpClientExtension.HttpUpdate(person);
            }
            catch (Exception ex)
            {
                _log.Here().Error(ex.GetBaseException().Message);
                TempData["error"] = ex.GetBaseException().Message;
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int personId)
        {
            try
            {
                await HttpClientExtension.HttpDelete("person", personId);
            }
            catch (Exception ex)
            {
                _log.Here().Error(ex.GetBaseException().Message);
                TempData["error"] = ex.GetBaseException().Message;
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Presentation/ExpertSender.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Test assignment for <a href="https://expertsender.pl/">ExpertSender</a>.</p>

    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Persons</h5>
            <p class="card-text">Module for simple CRUD actions on Person Entity.</p>
            <a class="btn btn-primary" asp-controller="Person" asp-action="Index">Person list</a>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Emails</h5>
            <p class="card-text">Module for simple CRUD actions on Email Entity.</p>
            <a class="btn btn-primary" asp-controller="Email" asp-action="Index">Email list</a>
          </div>
        </div>
      </div>
    </div>
</div>

Presentation/ExpertSender.WebApp/Views/Person/BasicForm.cshtml
@model ExpertSender.DTOs.PersonDTO

@{
    string title = "Update person";
    string action = "Update";

    if (Model == null)
    {
        title = "Create person";
        action = "Create";
    }

    ViewData["Title"] = title;
}

<h1>@title</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="@action">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">First Name</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Last Name</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group float-right">
                <a class="btn btn-primary" asp-action="Index">Back to List</a>
                <input type="submit" value="@action" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Presentation/ExpertSender.WebApp/Views/Person/Index.cshtml
@model IEnumerable<ExpertSender.DTOs.PersonDTO>

@{
    ViewData["Title"] = "Person list";
}

<h1>Person list</h1>

<p>
    <a class="btn btn-primary" asp-action="BasicForm">Create</a>
</p>

<div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Emails)
            </th>
            <th>
                <span>Options</span>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @if (!item.Emails.Any())
                    {
                        <span>N/A</span>
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.Emails.FirstOrDefault().EmailAddress)
                    }
                </td>
                <td>
                    <a class="btn btn-warning" asp-action="BasicForm" asp-route-personId="@item.Id">Update</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-personId="@item.Id" onclick="return confirm('Are you sure you want to delete person?')">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Presentation/ExpertSender.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpertSender.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExpertSender.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Persons</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Email" asp-action="Index">Emails</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - ExpertSender.WebApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>